#desafio1
print("projeto 01")
print(" Hello world! " * 5)
print("________________")

#desafio2
print(" \n Projeto 02 ")
print("  olá, meu nome é carlos ryan")
print("    _\|/_")
print("   ( °_° )")
print(" \n moro em Teresina-PI:")
print("        _____")
print("       (_____) ")
print("        /| |\ ") 
print("       / | | \ ")
print("      / /| |\ \ ")
print("     / / | | \ \ ")
print("    / / /| |\ \ \ ") 
print(" ———————————————————— ")
print("\n e gosto de gatos")
print(" _/\__/\_")
print("( ○ × ○ ) ")
print(" \n _______________")

#desafio3
print(" \n projeto 03 ")
print("  Brasil" * 2 )
print("  É Tetra," * 3)
print("  Tetra campeão" + "!" * 5 )
print("  Vai Bra" + "sil" * 6)
print(" \n _______________")

#desafio4
print("\n Projeto 04 ")
print("  parabéns amigo" + "!" *5 )
print(" \n Aqui vai um dinossauro \n \n")
print("             __")
print("            / °)")
print("     .-^^^-/ / ")
print("  __/       /")
print(" <__/|_|-|_|")
print(" \n quero bolo!")
print("¡"* 8)
print("#"* 10)
print("="*10)
print("#"*10)
print("="*10)